trigger:
  - main

variables:
  uiSource: 'src'

pool:
  name: Default
  agent: cicd-project-agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: CmdLine@2
    inputs:
      script: |
        npm install

  - task: CmdLine@2
    inputs:
      script: |
        npm run build

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/deploy.zip'
      replaceExistingArchive: true
  
  - script: |
      python.exe -m pip install --upgrade pip
    displayName: 'Update pip'

  - powershell: |
      Expand-Archive -Path $(Build.ArtifactStagingDirectory)/deploy.zip -DestinationPath $(Build.ArtifactStagingDirectory)/unzipped_artifacts
    displayName: 'Unzip Artifacts'

  # - script: |
  #     aws s3 sync $(Build.ArtifactStagingDirectory)/unzipped_artifacts s3://azure-cicd-connection-winjit/
  #   displayName: 'Upload Unzipped Artifacts'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'aws_iam_user'
      regionName: 'us-east-1'
      bucketName: 'azure-cicd-connection-winjit'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/unzipped_artifacts'
      globExpressions: '**'
      createBucket: true

