trigger:
  - main

pool:
  name: Default
  agent: cicd-project-agent

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      node app.js
    displayName: 'npm install and run'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/deploy.zip'
      replaceExistingArchive: true

  - script: |
      python.exe -m pip install --upgrade pip
    displayName: 'Update pip'

  - powershell: |
      Expand-Archive -Path $(Build.ArtifactStagingDirectory)/deploy.zip -DestinationPath $(Build.ArtifactStagingDirectory)/unzipped_artifacts
    displayName: 'Unzip Artifacts'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'Aws_RDS'
      regionName: 'us-east-1'
      bucketName: 'nodejs-rds-app-winjit'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/unzipped_artifacts'
      globExpressions: '**'
      createBucket: true
